name = "campamentopuntos"
pages_build_output_dir = "dist"
compatibility_date = "2024-08-05"

[[d1_databases]]
binding = "DB"
database_name = "db-puntos"
database_id = "2203fa30-c15d-4cee-815e-10bd356f1f07"